/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-menu.h
 #	source generated by 4D Plugin Wizard
 #	Project : menu
 #	author : miyako
 #	2025/08/06
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_MENU_H
#define PLUGIN_MENU_H

#include "4DPluginAPI.h"

#import <Cocoa/Cocoa.h>

#pragma mark -

static void INVOKE_MENU_ACTION(PA_PluginParameters params);

#endif /* PLUGIN_MENU_H */
